#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, 2015-2020


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
os: linux
language: shell
#This configuration can be validated at: https://config.travis-ci.com/explore


#*******************************************************************************
#Environment variables for different tests on multiple Travis CI workers 
#*******************************************************************************
env:
- TST_PUB_DWNL='travis_wait 30 ./tst_pub_dwnl_Emery_etal_2020_JHM2.sh' TST_PUB_REPR='travis_wait 30 ./tst_pub_repr_Emery_etal_2020_JHM2.sh'


#*******************************************************************************
#Before installing RRR
#*******************************************************************************
before_install:

#-------------------------------------------------------------------------------
#Create .netrc file for secure downloads (users need their own credentials)
#-------------------------------------------------------------------------------
- echo "machine urs.earthdata.nasa.gov login $NETRC_LOGIN_EDATA password $NETRC_PSWRD_EDATA" >> ~/.netrc

#-------------------------------------------------------------------------------
#Install operating system dependencies
#-------------------------------------------------------------------------------
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends $(grep -v -E '(^#|^$)' requirements.apt)

#-------------------------------------------------------------------------------
#General environment details
#-------------------------------------------------------------------------------
- apt-get --version
- apt list --installed
- which python
- python --version
- python -c "import site; print(site.getsitepackages())"


#*******************************************************************************
#Installing RRR
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- wget https://bootstrap.pypa.io/get-pip.py
- sudo python get-pip.py --no-cache-dir `grep 'pip==' requirements.pip` `grep 'setuptools==' requirements.pip` `grep 'wheel==' requirements.pip`
- rm get-pip.py
- which pip
- pip --version
- sudo pip install --no-cache-dir `grep 'numpy==' requirements.pip`
- sudo pip install --no-cache-dir -r requirements.pip


#*******************************************************************************
#Testing RRR 
#*******************************************************************************
script:
- cd $TRAVIS_BUILD_DIR
- cd ./tst/
- echo $TST_PUB_DWNL && $TST_PUB_DWNL
- echo $TST_PUB_REPR && $TST_PUB_REPR


#*******************************************************************************
#End
#*******************************************************************************
